language: julia
dist: bionic
os:
  - linux
arch:
  - x64
julia:
  - 1.4
jobs:
  allow_failures:
  - julia: nightly
  exclude:
    - os: osx
      arch: x86
    - os: osx
      arch: arm64
    - os: windows
      arch: arm64
    - julia: nightly
      arch: arm64
notifications:
  email: false

cache:
  directories:
  - $HOME/.julia/artifacts

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); cd(Pkg.dir("GSL")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
